blank_issues_enabled: false
contact_links:
  - name: 💬 Discord
    url: https://discord.gg/someengineering
    about: Chat with other users and the development team
  - name: 📄 Documentation
    url: https://docs.fix.tt
    about: Read and search documentation
